# Generated by Django 3.0.6 on 2020-05-10 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_count_user', models.IntegerField()),
                ('word_count_google', models.IntegerField()),
                ('tfidf_general_score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TfIdfResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=150)),
                ('user_score', models.FloatField()),
                ('google_score', models.FloatField()),
                ('analysis_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyser.AnalysisResult')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('job_status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('IN_QUEUE', 'In Queue'), ('RECEIVED', 'Received'), ('GOOGLE_SCRAPING_STARTED', 'Google Scraping Started'), ('URL_SCRAPING_STARTED', 'Url Scraping Started'), ('ANALYSIS_STARTED', 'Analysis Started'), ('SAVING', 'Saving'), ('COMPLETED', 'Completed')], default='CONFIRMED', max_length=250)),
                ('result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analyser.AnalysisResult')),
            ],
        ),
    ]
