# Generated by Django 3.0.6 on 2020-05-10 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyser', '0003_auto_20200510_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisjob',
            name='result',
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='analysis_instance',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='analyser.AnalysisJob'),
            preserve_default=False,
        ),
    ]
