# Generated by Django 3.0.6 on 2020-05-10 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyser', '0004_auto_20200510_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapingResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_user_article', models.BooleanField()),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('analysis_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyser.AnalysisJob')),
            ],
        ),
    ]
