# Generated by Django 3.0.6 on 2020-05-10 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyser', '0005_scrapingresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresult',
            name='analysis_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='analyser.AnalysisJob'),
        ),
        migrations.AlterField(
            model_name='tfidfresult',
            name='analysis_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tfidf_results', to='analyser.AnalysisResult'),
        ),
    ]
