# Generated by Django 3.0.6 on 2020-05-10 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyser', '0006_auto_20200511_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisjob',
            name='query',
            field=models.CharField(default='asdf', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='url',
            field=models.CharField(default='asdf.com', max_length=250),
            preserve_default=False,
        ),
    ]
