# Generated by Django 3.0.6 on 2020-05-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyser', '0008_auto_20200518_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisjob',
            name='jwt_token',
            field=models.CharField(default=111, max_length=500),
            preserve_default=False,
        ),
    ]
