# Generated by Django 3.0.6 on 2020-05-24 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyser', '0009_analysisjob_jwt_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisjob',
            name='jwt_token',
        ),
    ]
