# Generated by Django 3.0.6 on 2020-05-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyser', '0011_auto_20200525_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisjob',
            name='user_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
